---
- name: Fetch source code - Carbon
  git:
    repo: https://github.com/graphite-project/carbon.git
    dest: '{{ graphite_src_carbon }}'
    version: '{{ graphite_version }}'

- name: Create venv
  pip:
    virtualenv: '{{ graphite_venv }}'
    requirements: '{{ graphite_src_carbon }}/requirements.txt'
    virtualenv_python: python2.7

- name: Installing Carbon
  command: '{{ graphite_venv }}/bin/python setup.py install'
  args:
    chdir: '{{ graphite_src_carbon }}'
    creates: '{{ graphite_lib }}/bin/carbon-cache.py'

- name: Update are configuration files
  tags: graphite-cabon-conf
  template:
    src: '{{ item }}'
    dest: '{{ graphite_lib }}/conf/{{ item | basename }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - carbon/carbon.conf
    - carbon/storage-schemas.conf
    - carbon/storage-aggregation.conf
    - carbon/aggregation-rules.conf
  notify: restart carbon

- name: Update configuration file Supervisor
  tags: graphite-cabon-conf
  template:
    src: 'carbon/supervisor.conf'
    dest: '/etc/supervisor/conf.d/graphite-carbon.conf'
    owner: root
    group: root
    mode: 0644
  notify: restart carbon

- name: Initial at Supervisor
  supervisorctl:
    name: graphite-carbon
    state: present
