---
- name: Create directory
  file:
    dest: '{{ graphite_lib }}'
    state: directory
    owner: root
    group: root
    mode: 0755

- import_tasks: req.yml
- import_tasks: carbon.yml
- import_tasks: web.yml
