---
- name: Create user
  user:
    name: '{{ graphite_web_user }}'
    system: yes
    createhome: no

- name: Fetch source code - Web
  git:
    repo: https://github.com/graphite-project/graphite-web.git
    dest: '{{ graphite_src_web }}'
    version: '{{ graphite_version }}'

- name: Create venv
  pip:
    virtualenv: '{{ graphite_venv }}'
    requirements: '{{ graphite_src_web }}/requirements.txt'

- name: Installing Web
  command: '{{ graphite_venv }}/bin/python setup.py install'
  args:
    chdir: '{{ graphite_src_web }}'

- name: Create directory for sqlite db
  file:
    path: '{{ graphite_lib }}/storage/webapp'
    state: directory
    owner: '{{ graphite_web_user }}'
    group: '{{ graphite_web_user }}'
    mode: 0755

- name: Update config local_settings.py
  tags: graphite-web-conf
  template:
    src: web/local_settings.py
    dest: '{{ graphite_lib }}/webapp/graphite/local_settings.py'
    owner: root
    group: root
    mode: 0644

- name: Initial new DB
  shell: PYTHONPATH={{ graphite_lib }}/webapp {{ graphite_venv }}/bin/django-admin.py migrate --settings=graphite.settings --run-syncdb
  args:
    chdir: '{{ graphite_lib }}/webapp'
    creates: '{{ graphite_lib }}/storage/graphite.db'

- name: Check permission - directory
  command: 'chown {{ graphite_web_user }}:{{ graphite_web_user }} -R {{ item }}'
  with_items:
    - '{{ graphite_lib }}/storage/webapp'
    - '{{ graphite_lib }}/storage/log/webapp'

- name: Update configuration file Supervisor - web
  tags: graphite-web-conf
  template:
    src: web/supervisor.conf
    dest: /etc/supervisor/conf.d/graphite-web.conf
    owner: root
    group: root
    mode: 0644

- name: web - Initial at Supervisor
  supervisorctl:
    name: graphite-web
    state: present
